version: '3.9'

services:

   user-app:
     image: user-service-app
     container_name: user-service-app
     build:
       context: .
       dockerfile: ./user-service/Dockerfile
     ports:
       - "8081:8081"
     environment:
       DEPARTMENT_URL: "http://department-app:8080"

   department-app:
     image: department-service-app
     container_name: department-service-app
     build:
       context: .
       dockerfile: ./departement-service/Dockerfile
     ports:
       - "8080:8080"

   api-gateway:
     image: api-gateway-app
     container_name: api-gateway-app
     build:
       context: .
       dockerfile: ./api-gateway/Dockerfile
     ports:
       - "9001:9001"
     environment:
       DEPARTMENT_NAME: "http://department-app:8080"
       USER_SERVICE_NAME: "http://user-app:8081"