server:
  port: 9001

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/user/**

        - id: department-service
          uri: ${DEPARTMENT_URL:http://localhost:8080}
          predicates:
            - Path=/department/**


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG  # Enable debug logs for API Gateway
    org.springframework.web: DEBUG